package catalog

import (
	"fmt"
	"strings"
	"unicode"
)

func init() {
	if err := Validate(BaseRoutes(), Routes()); err != nil {
		panic(fmt.Sprintf("catalog startup validation failed: %v", err))
	}
}

// Validate ensures the hardcoded catalog invariants hold.
func Validate(base []Route, all []Route) error {
	if len(base) != 7 {
		return fmt.Errorf("expected exactly 7 base routes, got %d", len(base))
	}
	if len(all) != 28 {
		return fmt.Errorf("expected exactly 28 public aliases, got %d", len(all))
	}

	for _, route := range all {
		if route.Alias == "" {
			return fmt.Errorf("empty alias")
		}
		if strings.ContainsRune(route.Alias, '/') {
			return fmt.Errorf("alias %q contains invalid character '/': aliases may not contain slashes", route.Alias)
		}
		for _, r := range route.Alias {
			if unicode.IsSpace(r) {
				return fmt.Errorf("alias %q contains whitespace", route.Alias)
			}
		}
	}

	seen := make(map[string]bool)
	for _, route := range all {
		if seen[route.Alias] {
			return fmt.Errorf("duplicate public alias found: %s", route.Alias)
		}
		seen[route.Alias] = true

		if route.UpstreamModel == "" {
			return fmt.Errorf("empty upstream model for alias: %s", route.Alias)
		}

		if strings.ContainsRune(route.UpstreamModel, ' ') {
			return fmt.Errorf("upstream model %q contains a space", route.UpstreamModel)
		}

		if route.Injection != nil && route.Injection.Field == "messages" {
			return fmt.Errorf("injection targets messages for alias: %s", route.Alias)
		}
	}

	for _, route := range base {
		if len(route.EligibleAccounts) != 3 {
			return fmt.Errorf("base route %s does not reference exactly 3 accounts", route.Alias)
		}
		acctSeen := make(map[Account]bool)
		for _, acct := range route.EligibleAccounts {
			if acct != AccountK1 && acct != AccountK2 && acct != AccountK3 {
				return fmt.Errorf("invalid account %q in base route %s", acct, route.Alias)
			}
			acctSeen[acct] = true
		}
		if len(acctSeen) != 3 {
			return fmt.Errorf("base route %s does not reference all three accounts exactly once", route.Alias)
		}
	}

	for _, route := range all {
		if len(route.EligibleAccounts) == 3 {
			continue // Checked as base route above
		}
		if len(route.EligibleAccounts) != 1 {
			return fmt.Errorf("pinned route %s does not reference exactly one account", route.Alias)
		}
		acct := route.EligibleAccounts[0]
		if acct != AccountK1 && acct != AccountK2 && acct != AccountK3 {
			return fmt.Errorf("invalid account %q in pinned route %s", acct, route.Alias)
		}
	}

	// Other injection fields are allowed to exist, but the rules say "Only
	// the two declared pro routes inject reasoning_effort", so only that
	// field is counted and validated here.
	proInjections := 0
	for _, route := range base {
		if route.Injection != nil && route.Injection.Field == "reasoning_effort" {
			if route.Alias != "deepseek-v4-pro-max" && route.Alias != "deepseek-v4-pro-high" {
				return fmt.Errorf("route %s injects reasoning_effort but is not one of the declared pro routes", route.Alias)
			}
			proInjections++
		}
	}
	if proInjections != 2 {
		return fmt.Errorf("expected exactly 2 aliases to inject reasoning_effort, got %d", proInjections)
	}

	// Generated pinned routes match their base route's model and injection
	baseMap := make(map[string]Route)
	for _, b := range base {
		baseMap[b.Alias] = b
	}

	for _, route := range all {
		if len(route.EligibleAccounts) == 3 {
			continue // skip base
		}
		// pinned route name is baseAlias-account
		// It's generated by simply appending -k1, -k2, -k3
		baseAlias := route.Alias[:len(route.Alias)-3]
		br, ok := baseMap[baseAlias]
		if !ok {
			return fmt.Errorf("pinned route %s has no known base alias %s", route.Alias, baseAlias)
		}
		if route.UpstreamModel != br.UpstreamModel {
			return fmt.Errorf("pinned route %s has upstream model %q, expected base %q", route.Alias, route.UpstreamModel, br.UpstreamModel)
		}
		if br.Injection == nil {
			if route.Injection != nil {
				return fmt.Errorf("pinned route %s has injection, expected none", route.Alias)
			}
		} else {
			if route.Injection == nil || route.Injection.Field != br.Injection.Field || route.Injection.Value != br.Injection.Value {
				return fmt.Errorf("pinned route %s injection does not match base", route.Alias)
			}
		}
	}

	return nil
}
